name: docker-compose-phpunit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docker-compose-phpunit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker-compose images with cache
        run: |
          docker buildx build \
            --tag ghcr.io/${{ github.repository_owner }}/unity-dev-identity:latest \
            --cache-from type=registry,ref=ghcr.io/${{ github.repository_owner }}/unity-dev-identity:buildcache \
            --cache-to type=registry,ref=ghcr.io/${{ github.repository_owner }}/unity-dev-identity:buildcache,mode=max \
            --push \
            ./tools/docker-dev/identity

          docker buildx build \
            --tag ghcr.io/${{ github.repository_owner }}/unity-dev-sql:latest \
            --cache-from type=registry,ref=ghcr.io/${{ github.repository_owner }}/unity-dev-sql:buildcache \
            --cache-to type=registry,ref=ghcr.io/${{ github.repository_owner }}/unity-dev-sql:buildcache,mode=max \
            --push \
            ./tools/docker-dev/sql

          docker buildx build \
            --tag ghcr.io/${{ github.repository_owner }}/unity-dev-web:latest \
            --cache-from type=registry,ref=ghcr.io/${{ github.repository_owner }}/unity-dev-web:buildcache \
            --cache-to type=registry,ref=ghcr.io/${{ github.repository_owner }}/unity-dev-web:buildcache,mode=max \
            --push \
            ./tools/docker-dev/web

      - name: Pull cache images to local Docker
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/unity-dev-identity:latest
          docker tag ghcr.io/${{ github.repository_owner }}/unity-dev-identity:latest identity
          docker pull ghcr.io/${{ github.repository_owner }}/unity-dev-sql:latest
          docker tag ghcr.io/${{ github.repository_owner }}/unity-dev-sql:latest sql
          docker pull ghcr.io/${{ github.repository_owner }}/unity-dev-web:latest
          docker tag ghcr.io/${{ github.repository_owner }}/unity-dev-web:latest web
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer
      - run: composer install --dev
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./tools/docker-dev/docker-compose.yml"
      - run: docker compose -f ./tools/docker-dev/docker-compose.yml exec -w '/var/www/unity-web-portal' web bash -c 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover="$(mktemp --suffix=.xml)" -d --min-coverage=./coverage.php'
